### ISSUE TITLE
使用说明

### ISSUE THREAD

**Issue by wenbowen** [sbl1996/hinas#1]
你好大神，我是视觉方向的小白一枚，想请教一下能否出一个关于hinas这个项目的帮助文档呢，很多文件看不懂什么意思，甚至怎么运行这个项目也不会，万分感谢。

**Comment by sbl1996** [comment]
这是一个个人项目，主要是我本人对DARTS系列方法的实现，因为源码会经常做大幅度改动，所以没有时间维护文档。
DARTS系列入门建议从DARTS论文及DARTS的官方仓库开始: https://github.com/quark0/darts 另外也可参考Microsoft NNI中的实现: https://github.com/microsoft/nni/blob/master/docs/en_US/NAS/Overview.rst, 以及D-X-Y(多篇著名NAS论文作者)维护的这个仓库https://github.com/D-X-Y/AutoDL-Projects.

**Comment by wenbowen** [comment]
好的，十分感谢您的回复，我是做图像去噪方向研一新生，然后看到cvpr2020上有一篇用hinas做图像去噪，这篇论文没有提供源代码，不知道怎么入手，而且我看论文中自动搜索得到的神经网络的去噪效果还是没有达到目前去噪方面几个优秀人工设计的神经网络，我想看看有没有优化方式，这也是我的毕业方向，如果有相关教程那真的是太好了，没有也没关系，再次十分真诚感谢大神的教导




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sbl1996/hinas"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 上午9:55
收件人:&nbsp;"sbl1996/hinas"<hinas@noreply.github.com&gt;;
抄送:&nbsp;"万"<1936224653@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sbl1996/hinas] 使用说明 (#1)





 
这是一个个人项目，主要是我本人对DARTS系列方法的实现，因为源码会经常做大幅度改动，所以没有时间维护文档。
 DARTS系列入门建议从DARTS论文及DARTS的官方仓库开始: https://github.com/quark0/darts，另外也可参考Microsoft NNI中的实现: https://github.com/microsoft/nni/blob/master/docs/en_US/NAS/Overview.rst, 以及D-X-Y(多篇著名NAS论文作者)维护的这个仓库https://github.com/D-X-Y/AutoDL-Projects.

**Comment by sbl1996** [comment]
这是一个美丽的误会，你指的应该是HiNAS(Hierarchical NAS)，我这个仓库与HiNAS并没有任何关系，hi在这里仅仅是hello world的意思。如果那篇文章的代码没有开源，建议发邮件给作者索取，一般作者都会回复的。

**Comment by wenbowen** [comment]
这样啊，好吧，谢谢了
